// @generated by scripts/generate-remote-v2-contracts.ps1; DO NOT EDIT.
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
pub const GENERATED_CONTRACT_VERSION: u32 = 5;
pub const GENERATED_PROTOCOL_VERSION: u16 = 2;
pub const GENERATED_SUBPROTOCOL: &str = "vibelink-remote-v2";
pub const GENERATED_CONTRACT_SHA256: &str = "79564bef6dbb1ea408e81dc62ee874fbf440ae3f07dc10fcd7cf7c22c427707a";

pub const REMOTE_V2_METHODS: &[(&str, &[&str])] = &[
    ("agent", &["permission.resolve", "prompt", "sessions.list", "timeline"]),
    ("appearance", &["get"]),
    ("browser", &["back", "forward", "input.key", "input.pointer", "inspect", "navigate", "reload", "screencast.start", "screencast.stop", "screenshot", "tab.close", "tab.open", "tabs", "viewport.set"]),
    ("files", &["attachment.upload", "list", "read", "write"]),
    ("git", &["commit", "diff", "log", "stage", "status", "unstage"]),
    ("notifications", &["ack", "catchup", "register"]),
    ("orchestration", &["gate.resolve", "gates.list", "message.reply", "messages.list", "run.cancel", "runs.list", "task.retry", "tasks.list"]),
    ("system", &["resync", "status"]),
    ("terminal", &["ack", "close", "create", "input", "lease.claim", "lease.release", "lease.status", "snapshot", "subscribe", "unsubscribe"]),
    ("workspace", &["attach", "create", "detach", "list"]),
];

pub const REMOTE_V2_METHOD_NAMES: &[&str] = &[
    "agent.permission.resolve",
    "agent.prompt",
    "agent.sessions.list",
    "agent.timeline",
    "appearance.get",
    "browser.back",
    "browser.forward",
    "browser.input.key",
    "browser.input.pointer",
    "browser.inspect",
    "browser.navigate",
    "browser.reload",
    "browser.screencast.start",
    "browser.screencast.stop",
    "browser.screenshot",
    "browser.tab.close",
    "browser.tab.open",
    "browser.tabs",
    "browser.viewport.set",
    "files.attachment.upload",
    "files.list",
    "files.read",
    "files.write",
    "git.commit",
    "git.diff",
    "git.log",
    "git.stage",
    "git.status",
    "git.unstage",
    "notifications.ack",
    "notifications.catchup",
    "notifications.register",
    "orchestration.gate.resolve",
    "orchestration.gates.list",
    "orchestration.message.reply",
    "orchestration.messages.list",
    "orchestration.run.cancel",
    "orchestration.runs.list",
    "orchestration.task.retry",
    "orchestration.tasks.list",
    "system.resync",
    "system.status",
    "terminal.ack",
    "terminal.close",
    "terminal.create",
    "terminal.input",
    "terminal.lease.claim",
    "terminal.lease.release",
    "terminal.lease.status",
    "terminal.snapshot",
    "terminal.subscribe",
    "terminal.unsubscribe",
    "workspace.attach",
    "workspace.create",
    "workspace.detach",
    "workspace.list",
];

pub const REMOTE_V2_EVENTS: &[&str] = &[
    "agent.timeline.appended",
    "appearance.changed",
    "pane.state",
    "terminal.lease.changed",
    "terminal.lease.lost",
    "terminal.resized",
    "workspace.changed",
];

#[derive(Clone, Copy, Debug, Deserialize, Serialize, PartialEq, Eq)]
pub enum Activity {
    #[serde(rename = "idle")]
    Idle,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "waiting")]
    Waiting,
    #[serde(rename = "done")]
    Done,
    #[serde(rename = "error")]
    Error,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct AgentTimelineAppendedEvent {
    pub chat_id: String,
    pub first_sequence: u64,
    pub last_sequence: u64,
    pub workspace_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct AppearanceChangedEvent {
    pub appearance: AppearanceProjection,
    pub view_generation: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct AppearanceGetParams {
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct AppearanceProjection {
    pub alarm_highlight_color: String,
    pub cursor_style: CursorStyle,
    pub cursor_width: f64,
    pub font_family: String,
    pub font_size: f64,
    pub font_weight: String,
    pub font_weight_bold: String,
    pub reviewed_pane_highlight_color: String,
    pub scrollback: u32,
    pub selected_pane_highlight_color: String,
    pub terminal: TerminalTheme,
    pub theme_id: String,
    pub theme_name: String,
    pub ui_vars: StringMap,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct BrowserInspectParams {
    pub page_id: String,
    pub workspace_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub x: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub y: Option<f64>,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct BrowserInspectResult {
    pub snapshot_json: String,
    pub truncated: bool,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct BrowserKeyInput {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    pub r#type: BrowserKeyType,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct BrowserKeyParams {
    pub input: BrowserKeyInput,
    pub page_id: String,
    pub workspace_id: String,
}

#[derive(Clone, Copy, Debug, Deserialize, Serialize, PartialEq, Eq)]
pub enum BrowserKeyType {
    #[serde(rename = "text")]
    Text,
    #[serde(rename = "key")]
    Key,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct BrowserNavigateParams {
    pub page_id: String,
    pub url: String,
    pub workspace_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct BrowserPageParams {
    pub page_id: String,
    pub workspace_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct BrowserPointerInput {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub delta_x: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub delta_y: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub from_x: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub from_y: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub to_x: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub to_y: Option<f64>,
    pub r#type: BrowserPointerType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub x: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub y: Option<f64>,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct BrowserPointerParams {
    pub input: BrowserPointerInput,
    pub page_id: String,
    pub workspace_id: String,
}

#[derive(Clone, Copy, Debug, Deserialize, Serialize, PartialEq, Eq)]
pub enum BrowserPointerType {
    #[serde(rename = "tap")]
    Tap,
    #[serde(rename = "drag")]
    Drag,
    #[serde(rename = "scroll")]
    Scroll,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct BrowserScreencastStartParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_fps: Option<u16>,
    pub page_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub quality: Option<u16>,
    pub workspace_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct BrowserScreencastStartResult {
    pub height: u32,
    pub stream_id: u64,
    pub view_generation: u64,
    pub width: u32,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct BrowserScreencastStopParams {
    pub stream_id: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct BrowserScreenshotParams {
    pub page_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub quality: Option<u16>,
    pub workspace_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct BrowserScreenshotResult {
    pub data_base64: String,
    pub height: u32,
    pub view_generation: u64,
    pub width: u32,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct BrowserTab {
    pub id: String,
    pub title: String,
    pub url: String,
    pub workspace_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct BrowserTabCloseParams {
    pub page_id: String,
    pub workspace_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct BrowserTabCloseResult {
    pub closed: bool,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct BrowserTabOpenParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    pub workspace_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct BrowserTabResult {
    pub tab: BrowserTab,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct BrowserTabsParams {
    pub workspace_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct BrowserTabsResult {
    pub tabs: Vec<BrowserTab>,
}

#[derive(Clone, Copy, Debug, Deserialize, Serialize, PartialEq, Eq)]
pub enum BrowserViewportMode {
    #[serde(rename = "web")]
    Web,
    #[serde(rename = "mobile")]
    Mobile,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct BrowserViewportSetParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub center_x: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub center_y: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub device_scale_factor: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub height: Option<u32>,
    pub mode: BrowserViewportMode,
    pub page_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page_scale: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub width: Option<u32>,
    pub workspace_id: String,
}

#[derive(Clone, Copy, Debug, Deserialize, Serialize, PartialEq, Eq)]
pub enum CursorStyle {
    #[serde(rename = "bar")]
    Bar,
    #[serde(rename = "block")]
    Block,
    #[serde(rename = "underline")]
    Underline,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Empty {
}

pub type OpaqueObject = BTreeMap<String, serde_json::Value>;

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PaneStateEvent {
    pub pane: RemotePane,
    pub view_generation: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct RemotePane {
    pub activity: Activity,
    pub alive: bool,
    pub cols: u16,
    pub desktop_active: bool,
    pub group_id: String,
    pub group_order: u32,
    pub id: String,
    pub last_output_at: u64,
    pub order: u32,
    pub pane_generation: u64,
    pub role: String,
    pub rows: u16,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stream_id: Option<u64>,
    pub tab_order: u32,
    pub title: String,
    pub unread_count: u32,
    pub workspace_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct RemoteWorkspace {
    pub id: String,
    pub name: String,
    pub pane_count: u32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub workspace_folder: Option<String>,
}

pub type StringMap = BTreeMap<String, String>;

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct TerminalAckParams {
    pub sequence: u64,
    pub subscription_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct TerminalInputParams {
    pub data_base64: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lease_id: Option<String>,
    pub subscription_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct TerminalLeaseChangedEvent {
    pub lease: TerminalLeaseRecord,
    pub view_generation: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct TerminalLeaseClaimParams {
    pub cols: u16,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lease_id: Option<String>,
    pub pane_id: String,
    pub rows: u16,
    pub viewport_revision: u64,
    pub workspace_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct TerminalLeaseLostEvent {
    pub lease_id: String,
    pub lease_revision: u64,
    pub pane_id: String,
    pub reason: String,
    pub view_generation: u64,
    pub workspace_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct TerminalLeaseRecord {
    pub cols: u16,
    pub lease_id: String,
    pub lease_revision: u64,
    pub pane_id: String,
    pub rows: u16,
    pub viewport_revision: u64,
    pub workspace_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct TerminalLeaseReleaseParams {
    pub lease_id: String,
    pub lease_revision: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct TerminalLeaseStatusParams {
    pub pane_id: String,
    pub workspace_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct TerminalLeaseStatusResult {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lease: Option<TerminalLeaseRecord>,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct TerminalResizedEvent {
    pub cols: u16,
    pub pane_generation: u64,
    pub pane_id: String,
    pub rows: u16,
    pub view_generation: u64,
    pub workspace_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct TerminalSnapshotParams {
    pub reason: String,
    pub subscription_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct TerminalSnapshotResult {
    pub first_live_sequence: u64,
    pub pane_generation: u64,
    pub snapshot_bytes: u64,
    pub snapshot_chunks: u32,
    pub stream_id: u64,
    pub subscription_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct TerminalSubscribeParams {
    pub pane_id: String,
    pub view_generation: u64,
    pub workspace_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct TerminalSubscribeResult {
    pub alive: bool,
    pub cols: u16,
    pub first_live_sequence: u64,
    pub pane_generation: u64,
    pub rows: u16,
    pub snapshot_bytes: u64,
    pub snapshot_chunks: u32,
    pub stream_id: u64,
    pub subscription_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct TerminalTheme {
    pub background: String,
    pub black: String,
    pub blue: String,
    pub bright_black: String,
    pub bright_blue: String,
    pub bright_cyan: String,
    pub bright_green: String,
    pub bright_magenta: String,
    pub bright_red: String,
    pub bright_white: String,
    pub bright_yellow: String,
    pub cursor: String,
    pub cursor_accent: String,
    pub cyan: String,
    pub foreground: String,
    pub green: String,
    pub magenta: String,
    pub red: String,
    pub selection_background: String,
    pub white: String,
    pub yellow: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct TerminalUnsubscribeParams {
    pub subscription_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WorkspaceAttachParams {
    pub workspace_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WorkspaceAttachResult {
    pub panes: Vec<RemotePane>,
    pub view_generation: u64,
    pub workspace_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WorkspaceChangedEvent {
    pub view_generation: u64,
    pub workspaces: Vec<RemoteWorkspace>,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WorkspaceDetachParams {
    pub workspace_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WorkspaceListParams {
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WorkspaceListResult {
    pub view_generation: u64,
    pub workspaces: Vec<RemoteWorkspace>,
}

pub type AgentPermissionResolveParams = OpaqueObject;
pub type AgentPermissionResolveResult = OpaqueObject;
pub type AgentPromptParams = OpaqueObject;
pub type AgentPromptResult = OpaqueObject;
pub type AgentSessionsListParams = OpaqueObject;
pub type AgentSessionsListResult = OpaqueObject;
pub type AgentTimelineParams = OpaqueObject;
pub type AgentTimelineResult = OpaqueObject;
pub type AppearanceGetResult = AppearanceProjection;
pub type BrowserBackParams = BrowserPageParams;
pub type BrowserBackResult = BrowserTabResult;
pub type BrowserForwardParams = BrowserPageParams;
pub type BrowserForwardResult = BrowserTabResult;
pub type BrowserInputKeyParams = BrowserKeyParams;
pub type BrowserInputKeyResult = Empty;
pub type BrowserInputPointerParams = BrowserPointerParams;
pub type BrowserInputPointerResult = Empty;
pub type BrowserNavigateResult = BrowserTabResult;
pub type BrowserReloadParams = BrowserPageParams;
pub type BrowserReloadResult = BrowserTabResult;
pub type BrowserScreencastStopResult = Empty;
pub type BrowserTabOpenResult = BrowserTabResult;
pub type BrowserViewportSetResult = Empty;
pub type FilesAttachmentUploadParams = OpaqueObject;
pub type FilesAttachmentUploadResult = OpaqueObject;
pub type FilesListParams = OpaqueObject;
pub type FilesListResult = OpaqueObject;
pub type FilesReadParams = OpaqueObject;
pub type FilesReadResult = OpaqueObject;
pub type FilesWriteParams = OpaqueObject;
pub type FilesWriteResult = OpaqueObject;
pub type GitCommitParams = OpaqueObject;
pub type GitCommitResult = OpaqueObject;
pub type GitDiffParams = OpaqueObject;
pub type GitDiffResult = OpaqueObject;
pub type GitLogParams = OpaqueObject;
pub type GitLogResult = OpaqueObject;
pub type GitStageParams = OpaqueObject;
pub type GitStageResult = OpaqueObject;
pub type GitStatusParams = OpaqueObject;
pub type GitStatusResult = OpaqueObject;
pub type GitUnstageParams = OpaqueObject;
pub type GitUnstageResult = OpaqueObject;
pub type NotificationsAckParams = OpaqueObject;
pub type NotificationsAckResult = OpaqueObject;
pub type NotificationsCatchupParams = OpaqueObject;
pub type NotificationsCatchupResult = OpaqueObject;
pub type NotificationsRegisterParams = OpaqueObject;
pub type NotificationsRegisterResult = OpaqueObject;
pub type OrchestrationGateResolveParams = OpaqueObject;
pub type OrchestrationGateResolveResult = OpaqueObject;
pub type OrchestrationGatesListParams = OpaqueObject;
pub type OrchestrationGatesListResult = OpaqueObject;
pub type OrchestrationMessageReplyParams = OpaqueObject;
pub type OrchestrationMessageReplyResult = OpaqueObject;
pub type OrchestrationMessagesListParams = OpaqueObject;
pub type OrchestrationMessagesListResult = OpaqueObject;
pub type OrchestrationRunCancelParams = OpaqueObject;
pub type OrchestrationRunCancelResult = OpaqueObject;
pub type OrchestrationRunsListParams = OpaqueObject;
pub type OrchestrationRunsListResult = OpaqueObject;
pub type OrchestrationTaskRetryParams = OpaqueObject;
pub type OrchestrationTaskRetryResult = OpaqueObject;
pub type OrchestrationTasksListParams = OpaqueObject;
pub type OrchestrationTasksListResult = OpaqueObject;
pub type SystemResyncParams = OpaqueObject;
pub type SystemResyncResult = OpaqueObject;
pub type SystemStatusParams = OpaqueObject;
pub type SystemStatusResult = OpaqueObject;
pub type TerminalAckResult = Empty;
pub type TerminalCloseParams = OpaqueObject;
pub type TerminalCloseResult = OpaqueObject;
pub type TerminalCreateParams = OpaqueObject;
pub type TerminalCreateResult = OpaqueObject;
pub type TerminalInputResult = Empty;
pub type TerminalLeaseClaimResult = TerminalLeaseRecord;
pub type TerminalLeaseReleaseResult = Empty;
pub type TerminalUnsubscribeResult = Empty;
pub type WorkspaceCreateParams = OpaqueObject;
pub type WorkspaceCreateResult = OpaqueObject;
pub type WorkspaceDetachResult = Empty;
