import {
  Terminal,
  TerminalSquare,
  SquareTerminal,
  Command,
  Code,
  FileCode2,
  FileSearch,
  FolderTree,
  GitBranch,
  GitCompareArrows,
  History,
  MessagesSquare,
  Server,
  Database,
  Cloud,
  Folder,
  Sparkles,
  Bot,
  Zap,
  Flame,
  Rocket,
  RadioTower,
  Play,
  Cpu,
  Bug,
  Globe,
  GitCompare,
  LayoutGrid,
  ListTodo,
  MonitorCog,
} from 'lucide-react'

type IconComponent = typeof Terminal

export const profileIcons: Record<string, IconComponent> = {
  terminal: Terminal,
  'terminal-square': TerminalSquare,
  'square-terminal': SquareTerminal,
  command: Command,
  code: Code,
  'file-code': FileCode2,
  'file-search': FileSearch,
  'folder-tree': FolderTree,
  'git-branch': GitBranch,
  'git-compare-arrows': GitCompareArrows,
  history: History,
  'messages-square': MessagesSquare,
  server: Server,
  database: Database,
  cloud: Cloud,
  folder: Folder,
  sparkles: Sparkles,
  bot: Bot,
  zap: Zap,
  flame: Flame,
  rocket: Rocket,
  'radio-tower': RadioTower,
  play: Play,
  cpu: Cpu,
  bug: Bug,
  globe: Globe,
  'git-compare': GitCompare,
  'layout-grid': LayoutGrid,
  'list-todo': ListTodo,
  'monitor-cog': MonitorCog,
}

export const defaultProfileIconName = 'terminal'

export const profileIconNames = Object.keys(profileIcons)
